import type { RuleSetting } from "./types";

/**
 * Built-in preset rule sets.
 *
 * Each preset is a single flat rule set. All rules use `{ action: "redact" }`.
 */
export const BUILTIN_PRESETS: Record<
  string,
  ReadonlyArray<Readonly<Record<string, RuleSetting | "off">>>
> = {
  pii: [
    {
      email: { action: "redact" },
      phone: { action: "redact" },
      payment_card: { action: "redact" },
      us_ssn: { action: "redact" },
      uk_nino: { action: "redact" },
      ca_sin: { action: "redact" },
      au_tfn: { action: "redact" },
      jp_my_number: { action: "redact" },
      person_name_lite: { action: "redact" },
      passport: { action: "redact" },
      drivers_license: { action: "redact" },
      uk_nhs: { action: "redact" },
      us_itin: { action: "redact" },
      us_ein: { action: "redact" },
      nz_ird: { action: "redact" },
      iban: { action: "redact" },
      eu_vat: { action: "redact" },
      swift_bic: { action: "redact" },
      uk_sort_code: { action: "redact" },
      us_routing: { action: "redact" },
      uk_bank_account: { action: "redact" },
      address: { action: "redact" },
      postal_code: { action: "redact" },
      digital_identity: { action: "redact" },
      license_plate: { action: "redact" },
      de_id: { action: "redact" },
      fr_insee: { action: "redact" },
      it_codice_fiscale: { action: "redact" },
      es_dni: { action: "redact" },
      nl_bsn: { action: "redact" },
      pl_pesel: { action: "redact" },
      za_id: { action: "redact" },
      ng_nin: { action: "redact" },
      ng_bvn: { action: "redact" },
      ke_id: { action: "redact" },
      ke_kra_pin: { action: "redact" },
      eg_id: { action: "redact" },
      gh_card: { action: "redact" },
      ma_id: { action: "redact" },
      kz_iin: { action: "redact" },
      uz_passport: { action: "redact" },
      uz_stir: { action: "redact" },
      kg_pin: { action: "redact" },
      tj_id: { action: "redact" },
      tm_passport: { action: "redact" },
      ru_passport: { action: "redact" },
      ru_snils: { action: "redact" },
      ua_passport: { action: "redact" },
      ua_inn: { action: "redact" },
      cz_id: { action: "redact" },
      ro_cnp: { action: "redact" },
      hu_id: { action: "redact" },
      hu_tax_id: { action: "redact" },
      bg_egn: { action: "redact" },
      rs_jmbg: { action: "redact" },
      ar_dni: { action: "redact" },
      ar_cuit: { action: "redact" },
      cl_rut: { action: "redact" },
      co_cedula: { action: "redact" },
      co_nit: { action: "redact" },
      pe_dni: { action: "redact" },
      pe_ruc: { action: "redact" },
      ve_cedula: { action: "redact" },
      ve_rif: { action: "redact" },
      ec_cedula: { action: "redact" },
      uy_cedula: { action: "redact" },
      uae_id: { action: "redact" },
      sa_id: { action: "redact" },
      il_id: { action: "redact" },
      tr_id: { action: "redact" },
      qa_id: { action: "redact" },
      kw_id: { action: "redact" },
      bh_cpr: { action: "redact" },
      om_id: { action: "redact" },
      jo_id: { action: "redact" },
      lb_id: { action: "redact" },
      nz_driver_license: { action: "redact" },
      nz_passport: { action: "redact" },
      fj_id: { action: "redact" },
      png_id: { action: "redact" },
      ws_id: { action: "redact" },
      to_id: { action: "redact" },
      nz_ird_extra: { action: "redact" },
      id_nik: { action: "redact" },
      id_npwp: { action: "redact" },
      th_id: { action: "redact" },
      my_ic: { action: "redact" },
      ph_umid: { action: "redact" },
      vn_cccd: { action: "redact" },
      mm_nrc: { action: "redact" },
      crypto_address: { action: "redact" },
      health_insurance_id: { action: "redact" },
      vin: { action: "redact" },
      imei: { action: "redact" },
      imsi: { action: "redact" },
      tracking_number: { action: "redact" },
    },
  ],
  gdpr: [
    {
      email: { action: "redact" },
      phone: { action: "redact" },
      person_name_lite: { action: "redact" },
      iban: { action: "redact" },
      eu_vat: { action: "redact" },
      uk_nino: { action: "redact" },
      uk_nhs: { action: "redact" },
      uk_sort_code: { action: "redact" },
      uk_bank_account: { action: "redact" },
      swift_bic: { action: "redact" },
      drivers_license: { action: "redact" },
      passport: { action: "redact" },
      address: { action: "redact" },
      postal_code: { action: "redact" },
      digital_identity: { action: "redact" },
      license_plate: { action: "redact" },
      de_id: { action: "redact" },
      fr_insee: { action: "redact" },
      it_codice_fiscale: { action: "redact" },
      es_dni: { action: "redact" },
      nl_bsn: { action: "redact" },
      pl_pesel: { action: "redact" },
      cz_id: { action: "redact" },
      ro_cnp: { action: "redact" },
      hu_id: { action: "redact" },
      hu_tax_id: { action: "redact" },
      bg_egn: { action: "redact" },
      rs_jmbg: { action: "redact" },
      ru_passport: { action: "redact" },
      ru_snils: { action: "redact" },
      ua_passport: { action: "redact" },
      ua_inn: { action: "redact" },
      hr_identifier: { action: "redact" },
      hr_screening: { action: "redact" },
      hr_compensation: { action: "redact" },
      hr_recruitment: { action: "redact" },
      legal_case: { action: "redact" },
      legal_license: { action: "redact" },
      legal_reference: { action: "redact" },
    },
  ],
  hipaa: [
    {
      email: { action: "redact" },
      phone: { action: "redact" },
      payment_card: { action: "redact" },
      us_ssn: { action: "redact" },
      person_name_lite: { action: "redact" },
      passport: { action: "redact" },
      drivers_license: { action: "redact" },
      us_npi: { action: "redact" },
      us_dea: { action: "redact" },
      medical_record_number: { action: "redact" },
      uk_nhs: { action: "redact" },
      us_itin: { action: "redact" },
      us_ein: { action: "redact" },
      address: { action: "redact" },
      postal_code: { action: "redact" },
      digital_identity: { action: "redact" },
      health_insurance_id: { action: "redact" },
      medical_code: { action: "redact" },
      clinical_trial_id: { action: "redact" },
      medical_device_id: { action: "redact" },
      genetic_info: { action: "redact" },
      medical_reference: { action: "redact" },
      de_id: { action: "redact" },
      fr_insee: { action: "redact" },
      it_codice_fiscale: { action: "redact" },
      es_dni: { action: "redact" },
      nl_bsn: { action: "redact" },
      pl_pesel: { action: "redact" },
      license_plate: { action: "redact" },
    },
  ],
  ccpa: [
    {
      email: { action: "redact" },
      phone: { action: "redact" },
      payment_card: { action: "redact" },
      us_ssn: { action: "redact" },
      person_name_lite: { action: "redact" },
      address: { action: "redact" },
      postal_code: { action: "redact" },
      digital_identity: { action: "redact" },
      license_plate: { action: "redact" },
      uk_nino: { action: "redact" },
      ca_sin: { action: "redact" },
      au_tfn: { action: "redact" },
      jp_my_number: { action: "redact" },
      uk_nhs: { action: "redact" },
      us_itin: { action: "redact" },
      us_ein: { action: "redact" },
      nz_ird: { action: "redact" },
      de_id: { action: "redact" },
      fr_insee: { action: "redact" },
      it_codice_fiscale: { action: "redact" },
      es_dni: { action: "redact" },
      nl_bsn: { action: "redact" },
      pl_pesel: { action: "redact" },
      za_id: { action: "redact" },
      ng_nin: { action: "redact" },
      ng_bvn: { action: "redact" },
      ke_id: { action: "redact" },
      ke_kra_pin: { action: "redact" },
      eg_id: { action: "redact" },
      gh_card: { action: "redact" },
      ma_id: { action: "redact" },
      kz_iin: { action: "redact" },
      uz_passport: { action: "redact" },
      uz_stir: { action: "redact" },
      kg_pin: { action: "redact" },
      tj_id: { action: "redact" },
      tm_passport: { action: "redact" },
      ru_passport: { action: "redact" },
      ru_snils: { action: "redact" },
      ua_passport: { action: "redact" },
      ua_inn: { action: "redact" },
      cz_id: { action: "redact" },
      ro_cnp: { action: "redact" },
      hu_id: { action: "redact" },
      hu_tax_id: { action: "redact" },
      bg_egn: { action: "redact" },
      rs_jmbg: { action: "redact" },
      ar_dni: { action: "redact" },
      ar_cuit: { action: "redact" },
      cl_rut: { action: "redact" },
      co_cedula: { action: "redact" },
      co_nit: { action: "redact" },
      pe_dni: { action: "redact" },
      pe_ruc: { action: "redact" },
      ve_cedula: { action: "redact" },
      ve_rif: { action: "redact" },
      ec_cedula: { action: "redact" },
      uy_cedula: { action: "redact" },
      uae_id: { action: "redact" },
      sa_id: { action: "redact" },
      il_id: { action: "redact" },
      tr_id: { action: "redact" },
      qa_id: { action: "redact" },
      kw_id: { action: "redact" },
      bh_cpr: { action: "redact" },
      om_id: { action: "redact" },
      jo_id: { action: "redact" },
      lb_id: { action: "redact" },
      nz_driver_license: { action: "redact" },
      nz_passport: { action: "redact" },
      fj_id: { action: "redact" },
      png_id: { action: "redact" },
      ws_id: { action: "redact" },
      to_id: { action: "redact" },
      nz_ird_extra: { action: "redact" },
      id_nik: { action: "redact" },
      id_npwp: { action: "redact" },
      th_id: { action: "redact" },
      my_ic: { action: "redact" },
      ph_umid: { action: "redact" },
      vn_cccd: { action: "redact" },
      mm_nrc: { action: "redact" },
      vin: { action: "redact" },
      imei: { action: "redact" },
      imsi: { action: "redact" },
      tracking_number: { action: "redact" },
    },
  ],
  "pci-dss": [
    {
      payment_card: { action: "redact" },
      iban: { action: "redact" },
      card_data: { action: "redact" },
      financial_reference: { action: "redact" },
      investment_account: { action: "redact" },
      payment_gateway_id: { action: "redact" },
    },
  ],
  healthcare: [
    {
      email: { action: "redact" },
      phone: { action: "redact" },
      payment_card: { action: "redact" },
      us_ssn: { action: "redact" },
      person_name_lite: { action: "redact" },
      passport: { action: "redact" },
      drivers_license: { action: "redact" },
      us_npi: { action: "redact" },
      us_dea: { action: "redact" },
      medical_record_number: { action: "redact" },
      uk_nhs: { action: "redact" },
      address: { action: "redact" },
      postal_code: { action: "redact" },
      health_insurance_id: { action: "redact" },
      medical_code: { action: "redact" },
      clinical_trial_id: { action: "redact" },
      medical_device_id: { action: "redact" },
      genetic_info: { action: "redact" },
      medical_reference: { action: "redact" },
    },
  ],
  finance: [
    {
      email: { action: "redact" },
      phone: { action: "redact" },
      payment_card: { action: "redact" },
      iban: { action: "redact" },
      eu_vat: { action: "redact" },
      swift_bic: { action: "redact" },
      uk_sort_code: { action: "redact" },
      us_routing: { action: "redact" },
      uk_bank_account: { action: "redact" },
      financial_reference: { action: "redact" },
      investment_account: { action: "redact" },
      card_data: { action: "redact" },
      payment_gateway_id: { action: "redact" },
      crypto_address: { action: "redact" },
      crypto_tx_hash: { action: "redact" },
    },
  ],
  education: [
    {
      email: { action: "redact" },
      phone: { action: "redact" },
      us_ssn: { action: "redact" },
      person_name_lite: { action: "redact" },
      drivers_license: { action: "redact" },
      passport: { action: "redact" },
    },
  ],
  soc2: [
    {
      email: { action: "redact" },
      phone: { action: "redact" },
      payment_card: { action: "redact" },
      us_ssn: { action: "redact" },
      person_name_lite: { action: "redact" },
      ipv4: { action: "redact" },
      ipv6: { action: "redact" },
      mac_address: { action: "redact" },
      url_with_auth: { action: "redact" },
      aws_access_key: { action: "redact" },
      google_api_key: { action: "redact" },
      stripe_api_key: { action: "redact" },
      slack_token: { action: "redact" },
      github_token: { action: "redact" },
      jwt_token: { action: "redact" },
      private_key: { action: "redact" },
      generic_api_key: { action: "redact" },
      crypto_address: { action: "redact" },
      crypto_tx_hash: { action: "redact" },
      financial_reference: { action: "redact" },
      investment_account: { action: "redact" },
      card_data: { action: "redact" },
      payment_gateway_id: { action: "redact" },
      legal_case: { action: "redact" },
      legal_license: { action: "redact" },
      legal_reference: { action: "redact" },
      license_plate: { action: "redact" },
      vin: { action: "redact" },
      imei: { action: "redact" },
      imsi: { action: "redact" },
      http_auth_header: { action: "redact" },
      url_query_key: { action: "redact" },
      digitalocean_token: { action: "redact" },
      cloudflare_api_token: { action: "redact" },
      sendgrid_api_key: { action: "redact" },
      huggingface_token: { action: "redact" },
      slack_webhook_url: { action: "redact" },
      telegram_bot_token: { action: "redact" },
      gitlab_token: { action: "redact" },
      npm_token: { action: "redact" },
      openai_api_key: { action: "redact" },
      anthropic_api_key: { action: "redact" },
      shopify_token: { action: "redact" },
      twilio_sid: { action: "redact" },
      mailchimp_api_key: { action: "redact" },
      notion_token: { action: "redact" },
      sentry_token: { action: "redact" },
      heroku_api_key: { action: "redact" },
      linear_api_key: { action: "redact" },
      mailgun_api_key: { action: "redact" },
      okta_token: { action: "redact" },
      square_token: { action: "redact" },
      discord_bot_token: { action: "redact" },
      datadog_api_key: { action: "redact" },
      pagerduty_token: { action: "redact" },
      scaleway_key: { action: "redact" },
    },
  ],
  security: [
    {
      aws_access_key: { action: "redact" },
      google_api_key: { action: "redact" },
      stripe_api_key: { action: "redact" },
      slack_token: { action: "redact" },
      github_token: { action: "redact" },
      jwt_token: { action: "redact" },
      private_key: { action: "redact" },
      generic_api_key: { action: "redact" },
      ipv4: { action: "redact" },
      ipv6: { action: "redact" },
      mac_address: { action: "redact" },
      url_with_auth: { action: "redact" },
      crypto_address: { action: "redact" },
      crypto_tx_hash: { action: "redact" },
      http_auth_header: { action: "redact" },
      url_query_key: { action: "redact" },
      digitalocean_token: { action: "redact" },
      cloudflare_api_token: { action: "redact" },
      sendgrid_api_key: { action: "redact" },
      huggingface_token: { action: "redact" },
      slack_webhook_url: { action: "redact" },
      telegram_bot_token: { action: "redact" },
      gitlab_token: { action: "redact" },
      npm_token: { action: "redact" },
      openai_api_key: { action: "redact" },
      anthropic_api_key: { action: "redact" },
      shopify_token: { action: "redact" },
      twilio_sid: { action: "redact" },
      mailchimp_api_key: { action: "redact" },
      notion_token: { action: "redact" },
      sentry_token: { action: "redact" },
      heroku_api_key: { action: "redact" },
      linear_api_key: { action: "redact" },
      mailgun_api_key: { action: "redact" },
      okta_token: { action: "redact" },
      square_token: { action: "redact" },
      discord_bot_token: { action: "redact" },
      datadog_api_key: { action: "redact" },
      pagerduty_token: { action: "redact" },
      scaleway_key: { action: "redact" },
    },
  ],
};
